// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SanatGalerisi.Models;

#nullable disable

namespace SanatGalerisi.Migrations
{
    [DbContext(typeof(SanalSanatGalerisiDbContext))]
    [Migration("20240608150729_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SanatGalerisi.Models.Anasayfa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Aciklama")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Anasayfas");
                });

            modelBuilder.Entity("SanatGalerisi.Models.Galeri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Aciklama")
                        .HasColumnType("int");

                    b.Property<int>("Fotoid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Galeris");
                });

            modelBuilder.Entity("SanatGalerisi.Models.Nedir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Aciklama")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Nedirs");
                });
#pragma warning restore 612, 618
        }
    }
}
